### ISSUE TITLE
Consider renaming Codemirror.js to Codemirror.jsx

### ISSUE THREAD

**Issue by sporto** [JedWatson/react-codemirror#1]
I'm using webpack, because Codemirror.js extension is `js` but it contains JSX code, I need to pipe node_modules through babel. Maybe consider renaming this file to .jsx so the webpack config can ignore .js files in node_modules.

**Comment by JedWatson** [comment]
Sorry @sporto - that was actually a mistake in the package.json, which should be pointed at the `lib` folder instead (see #3)

Fixed now.
