### ISSUE TITLE
Not reacting to value change

### ISSUE THREAD

**Issue by FredrikNoren** [JedWatson/react-codemirror#110]
If I change `value` to something new, it's not reflected in the UI (nothing changes). After some debugging I think the culprit is this line: https://github.com/JedWatson/react-codemirror/blob/master/lib/Codemirror.js#L46
 
Because of that, the `nextProps.value !== this.props.value` equality is always false on line 68, because this.props.value has already been updated.

**Comment by besh** [comment]
I believe this PR fixed the issue 
https://github.com/JedWatson/react-codemirror/pull/107

**Comment by FredrikNoren** [comment]
Ah cool, thanks
