### ISSUE TITLE
clike mode is not working

### ISSUE THREAD

**Issue by osamajandali** [JedWatson/react-codemirror#113]
I Have used xml mode and works well for me and I have to add clike but it seems that it doesn't parse well, when i require it it changes the color so that's mean it works but can not see the code well and here is a screenshot.
<img width="533" alt="screen shot 2017-06-14 at 6 01 45 am" src="https://user-images.githubusercontent.com/13832392/27114938-70d60940-50c7-11e7-97ef-8a11c44aef53.png">

**Comment by TryingToImprove** [comment]
I have the same problem with java

**Comment by WxxShirley** [comment]
how do you fix this? @osamajandali
