### ISSUE TITLE
There has no .css file in lib?

### ISSUE THREAD

**Issue by zhangyu921** [JedWatson/react-codemirror#128]

**Comment by webgzh907247189** [comment]
demo:
import CodeMirror from 'react-codemirror'
import 'codemirror/addon/scroll/simplescrollbars.js'
import 'codemirror/addon/scroll/simplescrollbars.css'

**Comment by notten13** [comment]
Hi,

I'm having the same problem, after installing the module with npm I can't find any CSS files. How can I import the css in my app?

Many thanks
