### ISSUE TITLE
editor not displaying properly

### ISSUE THREAD

**Issue by shangsunset** [JedWatson/react-codemirror#14]
Hi the editor is not displaying properly for some reason. i did as the doc suggests. am i missing something? thanks.
![screen shot 2015-09-25 at 6 34 12 pm](https://cloud.githubusercontent.com/assets/3700269/10113626/6ed5f85a-63b4-11e5-9d51-ff9f3b280077.png)

**Comment by garrensmith** [comment]
@shangsunset that could mean you have not loaded the Codemirror css file.

**Comment by shangsunset** [comment]
@garrensmith yea thats the issue. thanks. do you know how to include/require addon and mode?

**Comment by shangsunset** [comment]
@garrensmith yea thats the issue. thanks a lot.
