### ISSUE TITLE
Does not highlight javascript text correctly

### ISSUE THREAD

**Issue by garrensmith** [JedWatson/react-codemirror#15]
If I want to display javascript with `react-codemirror` it doesn't correctly highlight the code to match the set theme. This is because you need to load the javascript background worker. Something like this:

`require('../node_modules/codemirror/mode/javascript/javascript');`

**Comment by cjhaddad** [comment]
@garrensmith is this setting the mode option to 'javascript' or using a MIME type? I've tried both 'javascript', 'text/javascript', and 'application/javascript' and even when I load the js background working file. it does not work. 
other question - have you syntax highlighting with json set to true? 


    mode: {
      name: 'application/javascript',
      json: true
    }

**Comment by garrensmith** [comment]
@cjhaddad I'm using webpack and all I do is after `require('react-codemirror')` the next line is `require('../node_modules/codemirror/mode/javascript/javascript');` and then it works for me.

**Comment by davedawson** [comment]
Thanks, @garrensmith. That solution worked for me!

@JedWatson, it may be helpful to include that info in the readme.

**Comment by codeuniquely** [comment]
I believe that you can just use

    require('react-codemirror');

    // Load various syntax files 
    require('codemirror/mode/python/python');
    require('codemirror/mode/tcl/tcl');
    require('codemirror/mode/javascript/javascript');

**Comment by JedWatson** [comment]
@codeuniquely that's correct. I've added this to the readme :)
