### ISSUE TITLE
Live demo is broken

### ISSUE THREAD

**Issue by n1k0** [JedWatson/react-codemirror#28]
Since 0.2.3 I guess 

http://jedwatson.github.io/react-codemirror/

**Comment by darkyen** [comment]
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

**Comment by JedWatson** [comment]
Not sure what went wrong with that build, but I've cleared all my local build caches and republished the latest version. It's working again. Thanks for the heads up :)
