### ISSUE TITLE
Update react to version 15.0

### ISSUE THREAD

**Issue by vslinko** [JedWatson/react-codemirror#42]
Today is the day when [first stable version of React is released](https://facebook.github.io/react/blog/2016/04/07/react-v15.html).
I hope that all popular instruments like this will support the new version soon.

**Comment by vslinko** [comment]
Created PR https://github.com/JedWatson/react-codemirror/pull/43

**Comment by JedWatson** [comment]
Merged and published! `v0.2.6` is compatible with React `^v15.0.0`, thanks for the PR!
