### ISSUE TITLE
When multiple Codemirror components exist on a page, only one can change the language

### ISSUE THREAD

**Issue by sslotsky** [JedWatson/react-codemirror#46]
I have a page that renders multiple instances of this component:

```jsx
import React, { PropTypes, Component } from 'react'
import CodeMirror from 'react-codemirror'
import 'codemirror/mode/jsx/jsx'
import 'codemirror/mode/javascript/javascript'
import 'codemirror/mode/ruby/ruby'

export class Snippet extends Component {
  static propTypes = {
    language: PropTypes.object,
    text: PropTypes.object
  }

  handleChange(text) {
    this.props.text.onChange(text)
  }

  changeLanguage(e) {
    this.props.language.onChange(e.target.value)
  }

  render() {
    return (
      <div>
        <select value={this.props.language.value} onChange={::this.changeLanguage}>
          <option value='jsx'>JSX</option>
          <option value='javascript'>JavaScript</option>
          <option value='ruby'>Ruby</option>
        </select>
        <CodeMirror options={{ mode: this.props.language.value, theme: 'erlang-dark' }} value={this.props.text.value} onChange={::this.handleChange} />
      </div>
    )
  }
}
```

It renders one for each entry in an array. The very bottom instance works perfectly. When I change my selection in the language dropdown, I can see the highlighting change as I expect. But all instances above the bottom instance reflect no change when I change their corresponding dropdown select.

There are no errors whatsoever. The `CodeMirror` instances seem to just be quietly ignoring the language change.

**Comment by sslotsky** [comment]
As a point of clarification, I've tried arrays of size 1, 2, and 3. In all cases, the bottom instance works, the top instances do not. I can link a repo if needed.

**Comment by sslotsky** [comment]
Here's a link to the repo if you need that to reproduce. Run `npm start` and then click on the `NEW POST` button on the sidebar and you'll see three snippets. In the top two snippets, the syntax highlighting does not change when you update the language.

https://github.com/sslotsky/redux-tech-blog

Nothing obvious stands out in this package's source and I've yet to attempt to step through due to time constraints.

**Comment by sslotsky** [comment]
Had a quick minute to step through the package's source code, and when I set a breakpoint in `componentWillReceiveProps` and update the language on my first snippet, I see that `this.codeMirror.getValue()` returns the text from the bottom snippet.

I've tried messing around with passing in the `codeMirrorInstance` but this is a problem because when this prop is passed in, an object is expected, but it seems that it's actually supposed to be a function. (https://github.com/JedWatson/react-codemirror/issues/45)

**Comment by sslotsky** [comment]
Aha, got to the bottom of this! It has to do with the `debounce` in the `componentWillReceiveProps` method of this package.

Since I was using `redux-form`, updating one snippet would update the form state, which would cause a re-rendering of _all_ snippets. And because `componentWillReceiveProps` is debounced, the function inside would only fire for the bottom snippet.

Workaround for my `Snippet` component:

```
  shouldComponentUpdate(nextProps) {
    return this.props.text.value != nextProps.text.value || this.props.language.value != nextProps.language.value
  }
```

Since the debouncing issue specifically is addressed in https://github.com/JedWatson/react-codemirror/issues/47 I will close this.

**Comment by Sunzhuoyi** [comment]
I did as you write when multiple codemirror on a page ,but it didn't work.
when it comes to that i delete the debounce it works well,but I don't know if there is something bad .
