### ISSUE TITLE
Line Numbers not rendering to gutter correctly.

### ISSUE THREAD

**Issue by jmunsch** [JedWatson/react-codemirror#6]
Using Browserify.

If I toggle the included css being pointed to the numbers display correctly.

![snapshot](https://cloud.githubusercontent.com/assets/2908235/8292513/b467dd48-18f5-11e5-8844-448703f5afc1.png)

Like this:
`.CodeMirror-gutter-elt {left: -29px !important}`

The line numbers display correctly, after I include the above line of css.

Possibly related areas of code:
https://github.com/JedWatson/react-codemirror/blob/master/lib/Codemirror.js#L23
https://github.com/JedWatson/react-codemirror/blob/master/dist/react-codemirror.js#L677-L678
https://github.com/JedWatson/react-codemirror/blob/master/dist/react-codemirror.js#L1052-L1063

I was also having difficulties with getting extra themes to work as well, since the className was not being appended to the correct elements.
```
var Editor         = require('./codeeditorview/CodeMirror')
    editorConfig: {
        'mode': 'javascript',
        'theme': 'cm-s-monokai',
        'lineNumbers': true,
    },
<Editor config={ this.items.editorConfig }/>
```

<b>./codeeditorview/CodeMirror':</b>
```
'use strict';
var Codemirror = require('react-codemirror');
var Editor = React.createClass({
    getInitialState: function() {
        return {
            code: 'function add(a, b) {\n' +
                  '  return a + b;\n' +
                  '}'
        };
    },
    updateCode: function(newCode) {
        console.log('From the editor',newCode)
        this.setState({
            code: newCode
        });
    },
    render: function() {
      var options = this.props.config
      return (
          <Codemirror value={this.state.code} onChange={this.updateCode} options={options} />
      )
    }
  });

// React.render(<App />, document.getElementById('app'));
module.exports = Editor
```

**Comment by travisperson** [comment]
Has anyone been able to figure this out completely? I am too running into this issue.

**Comment by ArnaudValensi** [comment]
I have the same issue too.

**Comment by devahome** [comment]
See http://dorianpula.ca/2015/10/07/adding-a-code-editor-to-rookeries/ for a possible answer. Dorian's suggestion worked for me. But highlighting is still MIA.

**Comment by devahome** [comment]
Should have read the example more carefully. The css in he example (https://github.com/JedWatson/react-codemirror/blob/master/example/src/example.less) includes the necessary css. Still looking for an answer to the highlighting issue - probably not specifying some option.

**Comment by Nicolewxyy** [comment]
I have the same issue even if I loaded the codemirror.css

**Comment by Nicolewxyy** [comment]
Use refresh or autorefresh to solve it. I require autorefresh.js and set option autoRefresh to true solved  it. 

- [https://github.com/codemirror/CodeMirror/issues/3098 ] See more details

**Comment by NEtOrnANtHeR** [comment]
Did you guys really solve this problem ?

I used `autoRefresh: true` and `import 'codemirror/addon/display/autorefresh';` , wrong rendering still  remains.

![image](https://cloud.githubusercontent.com/assets/11695765/23645104/6389760c-0345-11e7-9d9a-9f950708913e.png)

**Comment by davina18** [comment]
I tried refresh() instead and it worked.

Something like this:
`componentDidMount() {
	this.refs.editor.getCodeMirror().refresh();
`

**Comment by Pau1fitz** [comment]
@davina18  When I try this I get `Cannot read property 'getCodeMirror' of undefined`. Any ideas why?

**Comment by rootlinux2** [comment]
Thanks @Pau1fitz  it worked for me too

**Comment by ManuTheCoder** [comment]
I know my answer is late (and very old), but here is my solution
```
 .CodeMirror-gutters {
      left: 0 !important
  }
```
