### ISSUE TITLE
 Invariant Violation: addComponentAsRefTo

### ISSUE THREAD

**Issue by dnbard** [JedWatson/react-codemirror#7]
I've put `react-codemirror` to my project just almost the same as it described in example: 

```
var JSONBrowserPage = React.createClass({
    getInitialState: function(){
        return {
            options: {
                lineNumbers: true,
                mode: {name: "javascript", json: true}
            };
        };
    },

    render: function(){
        return (
            <Codemirror value={this.props.json} options={this.state.options}/>
        );
    }
});
```

and got next error:  
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

**Comment by steveluscher** [comment]
Fixed in #9.

**Comment by unformatt** [comment]
I'm getting this error with React 0.14.7 and react-codemirror 0.2.5

**Comment by ktalebian** [comment]
Any update on this?

**Comment by velveret** [comment]
See https://gist.github.com/jimfb/4faa6cbfb1ef476bd105 for some of the fixes that have worked for other people. In my case, I had to make react external in webpack.
