### ISSUE TITLE
Linenumber rendering issue

### ISSUE THREAD

**Issue by jonhue** [JedWatson/react-codemirror#81]
_Because all other issues regarding this topic were closed, I opened this new issue._

This is my CodeMirror instance:
[codemirror.txt](https://github.com/JedWatson/react-codemirror/files/661603/codemirror.txt)

I am using autorefresh and simplescrollbars.

I recorded the issue I am experiencing:
[Video](https://vimeo.com/196305264)

When starting the editor, the linenumbers look like:
[Image](https://cloud.githubusercontent.com/assets/2908235/8292513/b467dd48-18f5-11e5-8844-448703f5afc1.png)

**Comment by NEtOrnANtHeR** [comment]
@jonhue I think I 've met just the same issue like you did.
Why is this closed?

**Comment by NEtOrnANtHeR** [comment]
Got it. You should link #6

**Comment by jonhue** [comment]
I think it was a version specific issue, try changing you CodeMirror version.
