### ISSUE TITLE
Text selection problem: can't properly partially select text

### ISSUE THREAD

**Issue by NEtOrnANtHeR** [JedWatson/react-codemirror#91]
![image](https://cloud.githubusercontent.com/assets/11695765/23750856/c80fa5a4-0509-11e7-9d07-3003eafae219.png)

Value
```
SELECT trim(dbname) AS dbname, sql_text, query_time, lock_time, rows_sent
	, rows_examined, start_time, dbrole, dbuser, client
	, sql_type
FROM a.b t1
	JOIN (SELECT id
		FROM a.b t2
		WHERE ip = '100.81.152.9'
			AND port = '3314'
			AND start_time >= '2016-11-13 07:05:57'
			AND start_time <= '2016-11-13 13:05:57'
		) t2 ON t1.id = t2.id
ORDER BY start_time DESC
LIMIT 0, 40
```

Option
```
mode: "text/x-mysql",
readOnly: true,
autoRefresh: true,
lineWrapping: true,
lineNumbers: true,
viewportMargin: Infinity
```

Very simple options and value, but can't select text properly.

**The text selected has some backgroud color with unknown line-height, and can't find how to solve that by modifying css property**

Has anyone been through this before? Any advice will be appreciated.

### update 1

After a bit of digging, I found that CodeMirror is using divs with class of `CodeMirror-selected` to mark what is selected, and brings background of `#d9d9d9` with it.

![image](https://cloud.githubusercontent.com/assets/11695765/23751777/c3126312-050d-11e7-91cf-3a8e30ad0369.png)

Apparently, the "top" properties of class `.CodeMirror-selected` are incorrectly computed.

### update 2

With a little debugging, function `drawSelectionRange` at `react-codemirror/dist/react-codemirror.js:2958` 
is doing the range selection and it'll add div children with absolute position to make a mask of 'selection'.

### update 3

The calculation of `left` property of `.CodeMirror-selected` is dependent on the POSITION retriever of cursor position. However, postion of cursor is falsely set, referring to following snapshots.

3-1
![image](https://cloud.githubusercontent.com/assets/11695765/23753489/a717e018-0514-11e7-9a18-199aa4f968ec.png)

3-2
![image](https://cloud.githubusercontent.com/assets/11695765/23753512/b7140c1c-0514-11e7-9f20-cb3a67ea1dce.png)

Comparatively, snapshot 3-2 is more appropriate than snapshot 3-1 in user behaviour.

**Comment by NEtOrnANtHeR** [comment]
It's been found that some css property from parent componnent affected the position calculation of cursor.

**Comment by john-harding** [comment]
I recently had this same issue.  In my scenario, the `line-height` of my font was `17px`, and the `line-height` calculated by codemirror was `19px`.  To remedy this I used my custom theme which is named "custom-theme" and set all children elements to the `line-height` of `17px` as shown below.  Pretty simple but hope it helps someone in the future.


    .cm-s-custom-theme * {
        line-height: 17px;
    }

**Comment by levyadams** [comment]
@john-harding THANK YOU! I was using text as buttons for selection and only some of them were working. Messing with line-height I was able to make it so they were all easily clickable!

**Comment by levyadams** [comment]
Another thing I did was increase my z-index of the div element
