### ISSUE TITLE
Warning: CodeMirror: React.createClass is deprecated

### ISSUE THREAD

**Issue by lifeiscontent** [JedWatson/react-codemirror#98]
Hi, any ideas when this will be fixed?

Warning: CodeMirror: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by purplesquirrels** [comment]
There is a pull request that was created about 2 days ago to fix this. Hopefully it gets merged in soon.

**Comment by JedWatson** [comment]
It has been :)
