### ISSUE TITLE
Fix the version of the dependencies

### ISSUE THREAD

**Issue by callmemagnus** [JedWatson/react-codemirror#99]
For modules, as a user, I expect to obtain a module that will not change in time (as long as the version is not different).

I know that, in theory, the `^` should ensure backwards compatibility but I have experienced bad stuff with some module to then discover the issue was a dependency of dependency. Those issues would not have happened if the dependencies version were static (without ^ or ~).

What do you think?

**Comment by Janpot** [comment]
You can't control your dependency's dependencies. I think [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) is better suited for your use case.

**Comment by callmemagnus** [comment]
If everyone is resigned like that, it will never be solved, you are right. 

Shrinkwrap is annoying as it fixes also the source registry which may be problematic in corporate environments. 

The owner of this module will anyway decide what he wants to do with his module. 

I wish that more core module owner made the transition to fixing dependencies

**Comment by JedWatson** [comment]
Unfortunately if the versions were pinned more explicitly in this package, it would need to be republished every time there is a change or important fixes may not be available which is something I don't want to opt in to. And in any case, we have no control over the dependencies of our dependencies, so it would be an incomplete solution.

I recommend shrinkwrap or something with a lock file (yarn, npm 5) in production to solve this.

**Comment by callmemagnus** [comment]
okay, your module, your choice.
